### ISSUE TITLE
Short-term improvements

### ISSUE THREAD

**Issue by Vgr255** [Spireblight/Spireblight#99]
I have now returned to contracting for Baalor on a long-term basis, and, of course, part of that is hammering out all the lingering issues that have been around since the start, and try to get ahead of the technical debt that this project has slowly accrued.

### Short-term goals (before end of 2024)
- [ ] Complete work on #98 and merge it into main
- [ ] Implement #91 and #92 
- [ ] Properly make #66 into main, fixing the issues I had with it
- [ ] Actually look at (and maybe fix) and then merge #62 
- [ ] Untangle [the whole 1.0 Project page](https://github.com/orgs/Spireblight/projects/1/views/1) so that it actually reflects the goals, and to make 1.0 an actually-reachable goal, rather than just a Chekhov's Gun that never makes it to the final act

Once that last step is done, I'll close this issue and move progress tracking to, y'know, the thing that is designed for that.

If you have any suggestions as to what should be added to the progress board once I close this, comment here!
